# Generated by Django 4.0.5 on 2022-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='SportsApp.cartproduct', verbose_name='Товары для корзины'),
        ),
    ]
