# Generated by Django 4.0.5 on 2022-06-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0005_alter_customer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
